# Generated by Django 6.0.5 on 2026-05-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=100)),
                ('total_fee', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('pending_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('Interview', 'Interview'), ('Assessment', 'Assessment'), ('Technical Round', 'Technical Round'), ('HR Round', 'HR Round'), ('Selected', 'Selected'), ('Waiting For Offer', 'Waiting For Offer'), ('Offer Released', 'Offer Released'), ('Onboarding', 'Onboarding'), ('Welcome Mail', 'Welcome Mail'), ('Training', 'Training'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], max_length=100)),
            ],
        ),
    ]
